/**
 * An autogenerated component that renders the TAN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require("react");
const PropTypes = require("prop-types");

class Tan extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48">
                <g>
                    <title>Layer 1</title>
                    <text
                        transform="matrix(0.519322 0 0 0.519322 3.7771 6.35419)"
                        stroke="#000"
                        fontStyle="normal"
                        fontWeight="normal"
                        textAnchor="start"
                        fontFamily="'Poppins'"
                        fontSize="24"
                        y="43.94784"
                        x="21.03369"
                        fill="#000000"
                    >
                        ctg
                    </text>
                </g>
            </svg>
        );
    }
}

module.exports = Tan;
