/**
 * An autogenerated component that renders the DECIMAL iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Decimal = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Page-1" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="math_keypad_icon_radix_separator">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <path d="M23.9875,32.275 C24.9375,32.275 25.7375,31.475 25.7375,30.525 C25.7375,29.575 24.9375,28.775 23.9875,28.775 C23.0375,28.775 22.2375,29.575 22.2375,30.525 C22.2375,31.475 23.0375,32.275 23.9875,32.275 L23.9875,32.275 Z" id="." fill={this.props.primaryColor}></path>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Decimal;
