/**
 * An autogenerated component that renders the EXP_3 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Exp3 = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <defs>
                <rect id="path-1" x="14" y="20" width="12" height="16" rx="1"></rect>
                <mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="12" height="16" fill="white">
                    <use xlinkHref="#path-1"></use>
                </mask>
            </defs>
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1204.000000, -766.000000)">
                    <g id="math_keypad_icon_exponent_3" transform="translate(1204.000000, 766.000000)">
                        <g id="icon">
                            <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                            <use id="base" stroke={this.props.primaryColor} mask="url(#mask-2)" strokeWidth="4" xlinkHref="#path-1"></use>
                            <text id="3" fontFamily="ProximaNova-Extrabld, Proxima Nova" fontSize="10" fontWeight="600" fill={this.props.primaryColor}>
                                <tspan x="28" y="23">3</tspan>
                            </text>
                        </g>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Exp3;
