/**
 * An autogenerated component that renders the FRAC_MULTI iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const FracMulti = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1204.000000, -600.000000)">
                    <g id="math_keypad_icon_division_multi" transform="translate(1204.000000, 600.000000)">
                        <g>
                            <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                            <g id="fraction" transform="translate(6.000000, 12.000000)">
                                <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="24" height="24"></rect>
                                <path d="M8,16.9970301 C8,16.4463856 8.45303631,16 8.99703014,16 L15.0029699,16 C15.5536144,16 16,16.4530363 16,16.9970301 L16,23.0029699 C16,23.5536144 15.5469637,24 15.0029699,24 L8.99703014,24 C8.4463856,24 8,23.5469637 8,23.0029699 L8,16.9970301 Z M10,18 L14,18 L14,22 L10,22 L10,18 Z" id="block" fill={this.props.primaryColor}></path>
                                <rect id="bar" fill={this.props.primaryColor} x="2" y="11" width="20" height="2" rx="1"></rect>
                                <path d="M8,0.997030139 C8,0.446385598 8.45303631,0 8.99703014,0 L15.0029699,0 C15.5536144,0 16,0.453036308 16,0.997030139 L16,7.00296986 C16,7.5536144 15.5469637,8 15.0029699,8 L8.99703014,8 C8.4463856,8 8,7.54696369 8,7.00296986 L8,0.997030139 Z M10,2 L14,2 L14,6 L10,6 L10,2 Z" id="block" fill={this.props.primaryColor}></path>
                            </g>
                            <g id="division" opacity="0.6" transform="translate(34.000000, 12.000000)">
                                <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="8" height="8"></rect>
                                <circle id="dot" fill={this.props.primaryColor} cx="4" cy="7" r="1"></circle>
                                <path d="M1,4 L7,4" id="bar" stroke={this.props.primaryColor} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path>
                                <path d="M4,2 C4.55228475,2 5,1.55228475 5,1 C5,0.44771525 4.55228475,0 4,0 C3.44771525,0 3,0.44771525 3,1 C3,1.55228475 3.44771525,2 4,2 Z" id="dot" fill={this.props.primaryColor}></path>
                            </g>
                        </g>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = FracMulti;
