/**
 * An autogenerated component that renders the JUMP_OUT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const JumpOut = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <defs>
            <rect id="path-1" x="0" y="3" width="13" height="18" rx="2"></rect>
            <mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="13" height="18" fill="white">
                <use xlinkHref="#path-1"></use>
            </mask>
        </defs>
        <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="[Assets]-Math-Input" transform="translate(-1408.000000, -200.000000)">
                <g id="math_keypad_icon_jump_out" transform="translate(1408.000000, 200.000000)">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <g id="icon" strokeWidth="1" transform="translate(12.000000, 12.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="24" height="24"></rect>
                        <use id="Rectangle-356" stroke="#888D93" mask="url(#mask-2)" strokeWidth="4" xlinkHref="#path-1"></use>
                        <path d="M18,12 L9,12" id="tail" stroke="#78C008" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path>
                        <polyline id="head" stroke="#78C008" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" points="16 9 19 12 16 15"></polyline>
                        <path d="M23,4 L23,20" id="caret" stroke="#78C008" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path>
                        <path d="M5,8 L5,16" id="caret" stroke="#78C008" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path>
                    </g>
                </g>
            </g>
        </g>
    </svg>;
};

module.exports = JumpOut;
