/**
 * An autogenerated component that renders the LEFT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Left = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="[Assets]-Math-Input" transform="translate(-1272.000000, -200.000000)">
                <g id="math_keypad_icon_move_backward" transform="translate(1272.000000, 200.000000)">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <g id="arrow" strokeWidth="1" transform="translate(12.000000, 12.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="24" height="24"></rect>
                        <polyline id="head" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" points="10 6 4 12 10 18"></polyline>
                        <path d="M4,12 L20,12" id="tail" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path>
                    </g>
                </g>
            </g>
        </g>
    </svg>;
};

module.exports = Left;
