/**
 * An autogenerated component that renders the LEFT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Left = () => {
    return <svg width="48" height="48" viewBox="0 0 48 48"><g fill="none" fillRule="evenodd"><path fill="none" d="M0 0h48v48H0z"/><path fill="none" d="M12 12h24v24H12z"/><path stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" d="M22 18l-6 6 6 6M16 24h16"/></g></svg>;
};

module.exports = Left;
