/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Ln = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1340.000000, -766.000000)">
                    <g id="math_keypad_icon_log_e" transform="translate(1340.000000, 766.000000)">
                        <g id="icon">
                            <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                            <text id="ln" fontFamily="ProximaNova-Bold, Proxima Nova" fontSize="14" fontWeight="bold" fill={this.props.primaryColor}>
                                <tspan x="18.176" y="29">ln</tspan>
                            </text>
                        </g>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Ln;
