/**
 * An autogenerated component that renders the MINUS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Minus = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Page-1" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="math_keypad_icon_subtract">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <path d="M16,25 L32,25 C32.5522847,25 33,24.5522847 33,24 C33,23.4477153 32.5522847,23 32,23 L16,23 C15.4477153,23 15,23.4477153 15,24 C15,24.5522847 15.4477153,25 16,25 L16,25 Z" id="line" fill={this.props.primaryColor}></path>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Minus;
