/**
 * An autogenerated component that renders the MORE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const More = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="[Assets]-Math-Input" transform="translate(-1000.000000, -200.000000)">
                <g id="math_keypad_icon_on_page_numbers" transform="translate(1000.000000, 200.000000)">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <g id="symbols" strokeWidth="1" transform="translate(13.000000, 15.000000)" stroke="#888D93" strokeLinecap="round" strokeLinejoin="round">
                        <polyline id="radical" strokeWidth="2" points="14 15 16 19 20 11 22 11"></polyline>
                        <g id="equals" transform="translate(14.000000, 0.000000)" strokeWidth="2">
                            <path d="M0,1 L8,1" id="line"></path>
                            <path d="M0,5 L8,5" id="line"></path>
                        </g>
                        <g id="greater-than" strokeWidth="2">
                            <polyline id="line" points="0 0 8 3 0 6"></polyline>
                        </g>
                        <g id="less-than" transform="translate(4.000000, 15.000000) scale(-1, 1) translate(-4.000000, -15.000000) translate(0.000000, 12.000000)" strokeWidth="2">
                            <polyline id="line" points="0 0 8 3 0 6"></polyline>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </svg>;
};

module.exports = More;
