/**
 * An autogenerated component that renders the MORE iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const More = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <g id="Page-1" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="math_keypad_icon_advanced">
                <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                <circle id="dot" fill="#888D93" cx="15" cy="24" r="2"></circle>
                <circle id="dot" fill="#888D93" cx="23" cy="24" r="2"></circle>
                <circle id="dot" fill="#888D93" cx="31" cy="24" r="2"></circle>
            </g>
        </g>
    </svg>;
};

module.exports = More;
