/**
 * An autogenerated component that renders the NUM_6 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Num6 = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1408.000000, -298.000000)">
                    <g id="math_keypad_icon_6" transform="translate(1408.000000, 298.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                        <path d="M24.3125,32.3 C27.9625,32.3 30.1625,29.75 30.1625,26.85 C30.1625,23.3 27.7125,21.525 24.7125,21.525 C22.5625,21.525 20.7125,22.975 19.9875,24.125 C19.9625,23.9 19.9625,23.7 19.9625,23.475 C19.9625,20.2 21.4375,16.925 24.6625,16.925 C26.4125,16.925 27.3875,17.625 28.2375,18.625 L29.2875,17.075 C28.2625,15.9 26.8125,15.075 24.6625,15.075 C19.9875,15.075 17.8875,19.175 17.8875,23.7 C17.8875,28.225 19.6625,32.3 24.3125,32.3 L24.3125,32.3 Z M24.2375,30.45 C21.3375,30.45 20.2375,27.9 20.0375,25.825 C20.9625,24.35 22.5625,23.325 24.2125,23.325 C26.3625,23.325 28.0625,24.475 28.0625,26.925 C28.0625,28.525 26.8125,30.45 24.2375,30.45 L24.2375,30.45 Z" id="6" fill={this.props.primaryColor}></path>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Num6;
