/**
 * An autogenerated component that renders the NUM_5 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Num5 = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1340.000000, -298.000000)">
                    <g id="math_keypad_icon_5" transform="translate(1340.000000, 298.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                        <path d="M24.15,32.3 C27.5,32.3 30.075,30.2 30.075,26.8 C30.075,23.375 27.55,21.475 24.775,21.475 C23.1,21.475 21.675,22.175 20.875,22.975 L20.875,17.175 L29,17.175 L29,15.325 L18.8,15.325 L18.8,24.325 L20.325,24.85 C21.45,23.75 22.7,23.275 24.175,23.275 C26.425,23.275 28,24.675 28,26.875 C28,28.9 26.425,30.45 24.15,30.45 C22.1,30.45 20.65,29.65 19.55,28.25 L18.275,29.625 C19.525,31.275 21.325,32.3 24.15,32.3 L24.15,32.3 Z" id="5" fill={this.props.primaryColor}></path>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Num5;
