/**
 * An autogenerated component that renders the NUM_0 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Num0 = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1000.000000, -298.000000)">
                    <g id="math_keypad_icon_0" transform="translate(1000.000000, 298.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                        <path d="M24,32.3 C28.55,32.3 30.375,27.725 30.375,23.675 C30.375,19.6 28.55,15.075 24,15.075 C19.425,15.075 17.625,19.6 17.625,23.675 C17.625,27.725 19.425,32.3 24,32.3 L24,32.3 Z M24,30.45 C20.825,30.45 19.75,27 19.75,23.675 C19.75,20.35 20.825,16.925 24,16.925 C27.175,16.925 28.25,20.35 28.25,23.675 C28.25,27 27.175,30.45 24,30.45 L24,30.45 Z" id="0" fill={this.props.primaryColor}></path>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Num0;
