/**
 * An autogenerated component that renders the NUM_9 iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Num9 = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1612.000000, -298.000000)">
                    <g id="math_keypad_icon_9" transform="translate(1612.000000, 298.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                        <path d="M23.3375,32.275 C28.0125,32.275 30.1125,28.175 30.1125,23.675 C30.1125,19.125 28.3375,15.05 23.6625,15.05 C20.0375,15.05 17.8375,17.625 17.8375,20.5 C17.8375,24.05 20.3125,25.825 23.3125,25.825 C25.4375,25.825 27.2875,24.375 28.0125,23.225 C28.0375,23.45 28.0375,23.675 28.0375,23.9 C28.0375,27.05 26.7125,30.425 23.3375,30.425 C21.6125,30.425 20.6125,29.725 19.7625,28.725 L18.7125,30.275 C19.7625,31.475 21.2125,32.275 23.3375,32.275 L23.3375,32.275 Z M23.7875,24.025 C21.6375,24.025 19.9375,22.875 19.9375,20.425 C19.9375,18.85 21.2125,16.9 23.7625,16.9 C26.6625,16.9 27.7625,19.475 27.9375,21.55 C27.0625,23.025 25.4375,24.025 23.7875,24.025 L23.7875,24.025 Z" id="9" fill={this.props.primaryColor}></path>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = Num9;
