/**
 * An autogenerated component that renders the NUMBERS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Numbers = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="[Assets]-Math-Input" transform="translate(-1068.000000, -200.000000)">
                <g id="math_keypad_icon_on_page_symbols" transform="translate(1068.000000, 200.000000)">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                    <g id="arithmetic" strokeWidth="1" transform="translate(13.000000, 13.000000)">
                        <g id="divide" transform="translate(14.000000, 13.000000)">
                            <path d="M0,5 L8,5" id="line" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path>
                            <circle id="Oval-30" fill="#888D93" cx="4" cy="1.5" r="1.5"></circle>
                            <circle id="Oval-30" fill="#888D93" cx="4" cy="8.5" r="1.5"></circle>
                        </g>
                        <g id="multiply" transform="translate(1.000000, 15.000000)" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <path d="M0,6 L6,0" id="line"></path>
                            <path d="M0,0 L6,6" id="line"></path>
                        </g>
                        <g id="subtract" transform="translate(14.000000, 3.000000)" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <path d="M0,1 L8,1" id="line"></path>
                        </g>
                        <g id="add" stroke="#888D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <path d="M4,8 L4,0" id="line"></path>
                            <path d="M0,4 L8,4" id="line"></path>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </svg>;
};

module.exports = Numbers;
