/**
 * An autogenerated component that renders the RIGHT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const Right = () => {
    return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
        <g id="Page-1" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
            <g id="math_keypad_icon_escape">
                <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                <g id="arrow" transform="translate(12.000000, 12.000000)">
                    <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="24" height="24"></rect>
                    <path d="M17,10 L17,18 L18,17 L10,17 C9.44771525,17 9,17.4477153 9,18 C9,18.5522847 9.44771525,19 10,19 L18,19 C18.5522847,19 19,18.5522847 19,18 L19,10 C19,9.44771525 18.5522847,9 18,9 C17.4477153,9 17,9.44771525 17,10 L17,10 Z" id="head" fill="#888D93"></path>
                    <path d="M5.29289322,6.70710678 L17.2928932,18.7071068 C17.6834175,19.0976311 18.3165825,19.0976311 18.7071068,18.7071068 C19.0976311,18.3165825 19.0976311,17.6834175 18.7071068,17.2928932 L6.70710678,5.29289322 C6.31658249,4.90236893 5.68341751,4.90236893 5.29289322,5.29289322 C4.90236893,5.68341751 4.90236893,6.31658249 5.29289322,6.70710678 L5.29289322,6.70710678 Z" id="tail" fill="#888D93"></path>
                </g>
            </g>
        </g>
    </svg>;
};

module.exports = Right;
