/**
 * An autogenerated component that renders the TOGGLE_SIGN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const ToggleSign = React.createClass({
    propTypes: {
        color: React.PropTypes.string.isRequired,
    },

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48"><g fill="none" fillRule="evenodd"><path fill="none" d="M0 0h48v48H0z"/><path fill="none" d="M12 12h24v24H12z"/><path d="M27 28h8M28 16l-8 16" stroke={this.props.color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><g stroke={this.props.color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 20h8M17 16v8"/></g></g></svg>;
    },
});

module.exports = ToggleSign;
