/**
 * An autogenerated component that renders the x iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

const X = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return <svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1">
            <g id="Math-Input" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <g id="[Assets]-Math-Input" transform="translate(-1340.000000, -600.000000)">
                    <g id="icon" transform="translate(1340.000000, 600.000000)">
                        <rect id="bounds" fillOpacity="0" fill="#FF0088" x="0" y="0" width="48" height="48"></rect>
                        <polygon id="x" fill={this.props.primaryColor} points="28.82 30 25.26 25.04 28.6 20.34 26.24 20.34 23.96 23.62 21.66 20.34 19.3 20.34 22.64 25.04 19.1 30 21.44 30 23.96 26.44 26.46 30"></polygon>
                    </g>
                </g>
            </g>
        </svg>;
    },
});

module.exports = X;
