version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test
workflows:
  version: 2
  test:
    jobs:
      - test
