import os
import re
import sys
import symbol_map

primaryColor = '#3B3E40'
secondaryColor = '#BABEC2'

header = '''/**
 * An autogenerated component that renders the %s iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');
'''

# A simple template with no PropTypes, for the case in which there are no
# colors in the component.
simple_template = header + '''
const %s = () => {
    return %s;
};

module.exports = %s;
'''
complex_template = header + '''
const %s = React.createClass({
    propTypes: {
        primaryColor: React.PropTypes.string,
        secondaryColor: React.PropTypes.string,
    },

    getDefaultProps() {
        return {
            primaryColor: '#3B3E40',
            secondaryColor: '#BABEC2',
        };
    },

    render() {
        return %s;
    },
});

module.exports = %s;
'''

index_template = '''/**
 * A directory of autogenerated icon components.
 */

module.exports = {
%s
};
'''

if __name__ == '__main__':
    input_dir_name = sys.argv[1]
    output_dir_name = sys.argv[2]

    filename_map = {}

    for filename in os.listdir(input_dir_name):
        use_simple = True

        svg_filename = filename.split('/')[-1].split('.')[0]

        prefix = 'math-keypad-icon-'
        if svg_filename[:len(prefix)] == prefix:
            svg_filename = svg_filename[len(prefix):]
        else:
            continue

        try:
            symbol_name = symbol_map.filename_to_symbol[svg_filename]
        except:
            print 'Skipping: ' + svg_filename
            continue

        component_name = symbol_name.title().replace('_', '')
        js_filename = symbol_name.lower().replace('_', '-')

        with open(input_dir_name + '/' + filename, 'r') as f:
            contents = ''
            for line in f:
                # Ignore unnecessary lines
                if '<title>' in line or '<desc>' in line or '<?xml' in line or '<!--' in line or '<defs></defs>' in line:
                    continue

                # Special-case the first line, since we don't want to indent it, and we need to strip the namespace tags.
                if '<svg' in line:
                    start_namespace = line.index('xmlns')
                    line = line[:start_namespace - 1] + '>' + '\n'
                    contents += line
                else:
                    contents += line

            # Replace colors
            before = contents
            contents = re.sub('"' + primaryColor + '"', '{this.props.primaryColor}',
                re.sub('"' + secondaryColor + '"', '{this.props.secondaryColor}', contents))
            if before != contents:
                use_simple = False

            # Replace the xlin:href tag (special case)
            contents = contents.replace('xlink:href', 'xlinkHref')
            # Replace any other tags
            tags = re.findall(r' (\S+)=', contents)
            for tag in tags:
                pieces = tag.split('-')
                jsx_version = pieces[0] + ''.join(map(lambda x: x.title(), pieces[1:]))
                contents = contents.replace(tag, jsx_version)

        with open(output_dir_name + '/' + js_filename + '.js', 'w') as f:
            template = simple_template if use_simple else complex_template

            # Indent lines properly
            indent = '    ' if use_simple else '        '
            lines = contents.split('\n')
            contents = lines[0] + '\n' + '\n'.join(map(lambda x: indent + x, lines[1:]))

            f.write(template % (symbol_name, component_name, contents, component_name))

        filename_map[symbol_name] = js_filename

    index_contents = ''
    for symbol_name in filename_map:
        if index_contents:
            index_contents += '\n'
        index_contents += '    %s: require(\'./%s\'),' % (symbol_name, filename_map[symbol_name])

    with open(output_dir_name + '/index.js', 'w') as f:
        f.write(index_template % index_contents)
