
filename_to_symbol = {
    'addition': 'PLUS',
    'subtraction': 'MINUS',
    'cos': 'COS',
    'sin': 'SIN',
    'tan': 'TAN',
    'delete': 'BACKSPACE',
    'dismiss': 'DISMISS',
    'division': 'DIVIDE',
    'equals': 'EQUAL',
    'equals-not': 'NEQ',
    'exponent-2': 'EXP_2',
    'exponent-3': 'EXP_3',
    'exponent': 'EXP',
    'fraction': 'FRAC',
    'greater-than-not': 'GEQ',
    'greater-than': 'GT',
    'less-than-not': 'LEQ',
    'less-than': 'LT',
    'log-10': 'LOG',
    'log-e': 'LN',
    'log': 'LOG_N',
    'move-backward': 'ARROW',
    'parenthesis-left': 'LEFT_PAREN',
    'parenthesis-right': 'RIGHT_PAREN',
    'jump-out': 'JUMP_OUT',
    'multiplication-cross': 'TIMES',
    'multiplication-dot': 'CDOT',
    'percent': 'PERCENT',
    'negate': 'TOGGLE_SIGN',
    'radix-character': 'DECIMAL',
    'radical': 'RADICAL',
    'radical-2': 'SQRT',
    'radical-3': 'CUBE_ROOT',
}
